import { execSync } from "node:child_process";
import { createHash } from "node:crypto";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

/**
 * ATLAS REPRODUCIBILITY — does regenerating produce the same bytes?
 *
 *   npm run atlas:verify
 *
 * WHY. The committed operators atlas could not be regenerated: nobody had
 * recorded the flags, and the tool's defaults produce a different frame size
 * and a different WebP. An asset whose build command is unknown cannot be
 * maintained — the next person to touch the art has to reverse-engineer the
 * invocation from the output, which is what this run had to do.
 *
 * It turned out the pipeline WAS deterministic; only the invocation was
 * missing. `--size 360` (120 design px at 3x DPR, per §8) and `--names`, and
 * every byte matches. That is worth keeping true, so this regenerates each
 * family from the recorded npm script and compares hashes.
 *
 * This is a CHECK, not a build step: it restores the working tree afterwards
 * so a verification run never leaves modified assets behind.
 */
const DIR = "public/assets/sprites";
const FAMILIES = ["operators", "operators-unlit", "tiles", "plaques", "automaton"];

const hash = (file) => createHash("sha256").update(readFileSync(file)).digest("hex").slice(0, 16);

const before = new Map();
for (const name of readdirSync(DIR)) before.set(name, hash(join(DIR, name)));

process.stdout.write("\nregenerating every atlas from its recorded script\n");
for (const family of FAMILIES) {
  execSync(`npm run atlas:${family}`, { stdio: "pipe" });
}

const failures = [];
for (const name of readdirSync(DIR)) {
  const now = hash(join(DIR, name));
  const was = before.get(name);
  if (was === undefined) {
    failures.push(`${name}: appeared only after regeneration`);
    continue;
  }
  const same = was === now;
  process.stdout.write(`  ${same ? "same" : "DIFF"}  ${name.padEnd(20)} ${was} -> ${now}\n`);
  if (!same) failures.push(`${name}: ${was} -> ${now}`);
}
for (const name of before.keys()) {
  if (!readdirSync(DIR).includes(name)) failures.push(`${name}: disappeared after regeneration`);
}

if (failures.length > 0) {
  process.stdout.write(
    `\natlases are NOT reproducible:\n  ${failures.join("\n  ")}\n` +
      `\nThis is a bug in the pipeline or a missing flag in the npm script, not a\n` +
      `fact to document. Find the nondeterminism rather than committing the new bytes.\n`,
  );
  process.exit(1);
}

process.stdout.write("\nevery atlas regenerated byte-identically\n");
